export const MODAL__TASK_EXISTS = 'MODAL__TASK_EXISTS';
export const MODAL__EMPTY_VALUE = 'MODAL__EMPTY_VALUE';
export const MODAL__DELETE_TASK_CONFIRM = 'MODAL__DELETE_TASK_CONFIRM';
export const MODAL__DELETE_TASKLIST_CONFIRM = 'MODAL__DELETE_TASKLIST_CONFIRM';
